### ISSUE TITLE
大佬，求解答

### ISSUE THREAD

**Issue by MZY888** [mrzhqiang/rowing#3]
问题出现在rowing-master\src\main\java\com\github\mrzhqiang\rowing\account\RegisterController.java在33行isPresent()
java: 无法取消引用void,试了几个方法还是不行

**Comment by mrzhqiang** [comment]
目前的版本没有经过测试，建议使用 https://github.com/mrzhqiang/rowing/commit/36f25c103b3dc2512acd9917dd093f240620c9e0
版本或之后的提交版本。

**Comment by MZY888** [comment]
> 目前的版本尚未经过测试，建议使用[36f25c1](https://github.com/mrzhqiang/rowing/commit/36f25c103b3dc2512acd9917dd093f240620c9e0) 版本或之后的提交版本。

目前使用的就是最新提交的

**Comment by mrzhqiang** [comment]
> > 目前的版本尚未经过测试，建议使用[36f25c1](https://github.com/mrzhqiang/rowing/commit/36f25c103b3dc2512acd9917dd093f240620c9e0) 版本或之后的提交版本。
> 
> 目前使用的就是最新提交的

请使用我上面提供的版本

**Comment by MZY888** [comment]
> > > 目前的版本尚未经过测试，建议使用[36f25c1](https://github.com/mrzhqiang/rowing/commit/36f25c103b3dc2512acd9917dd093f240620c9e0)版本或之后的提交版本。
> > 
> > 
> > 目前使用的就是最新提交的
> 
> 请使用我上面提供的版本

**Comment by MZY888** [comment]
> > > > 目前的版本尚未经过测试，建议使用[36f25c1](https://github.com/mrzhqiang/rowing/commit/36f25c103b3dc2512acd9917dd093f240620c9e0)版本或之后的提交版本。
> > > 
> > > 
> > > 目前使用的就是最新提交的
> > 
> > 
> > 请使用我上面提供的版本

OK了，感谢佬，不过初始登录的密码是啥呀，还是需要自己新建
