### ISSUE TITLE
大佬，成功跑起来了，十分感谢，不过密码是啥呀

### ISSUE THREAD

**Issue by MZY888** [mrzhqiang/rowing#4]

**Comment by mrzhqiang** [comment]
在项目目录有个admin.txt文件就是密码

**Comment by MZY888** [comment]
> 在项目目录有一个admin.txt文件就是密码

好的，感谢

**Comment by MZY888** [comment]
> > > 在项目目录中有一个admin.txt文件就是密码
> > 
> > 
> > 大佬又要麻烦你了，之后我打开是那个框架的网站，怎么才能打开是考试网站
> 
> 管理后台创建相关用户，比如看到候选人阅读卷官，给予角色，然后选择菜单。之后就可以考试和阅读卷的页面或者。做的比较粗糙，你可以优化一下页面。

不行呀，佬，admin登录之后没有这些

**Comment by mrzhqiang** [comment]
> > > > 在项目目录中有一个admin.txt文件就是密码
> > > 
> > > 
> > > 大佬又要麻烦你了，之后我打开是那个框架的网站，怎么才能打开是考试网站
> > 
> > 管理后台创建相关用户，比如看到候选人阅读卷官，给予角色，然后选择菜单。之后就可以考试和阅读卷的页面或者。做的比较粗糙，你可以优化一下页面。
> 
> 不行呀，佬，admin登录之后没有这些

你提供截图

**Comment by MZY888** [comment]
> > > > > 在项目目录中有一个admin.txt文件就是密码
> > > > 
> > > > 
> > > > 大佬又要麻烦你了，之后我打开是那个框架的网站，怎么才能打开是考试网站
> > > 
> > > 
> > > 管理后台相关用户，比如看到候选人阅读卷官，给出角色，然后选择菜单。之后就可以考试和阅读卷的页面或者。做比较粗糙的创建，你可以优化一下页面。
> > 
> > 
> > 不行呀，老兄，管理登录之后就没有这些了
> 
> 您提供截图

![QQ截图20240302210312](https://github.com/mrzhqiang/rowing/assets/113449126/d3a25ecb-02cd-449c-a2fe-a77709c84ed8)
![QQ截图20240302210342](https://github.com/mrzhqiang/rowing/assets/113449126/0a3e7294-e754-4001-af1d-a8651fd308aa)

**Comment by mrzhqiang** [comment]
应该是你没有正常初始化菜单，你看看菜单表里面有没有数据？

**Comment by mrzhqiang** [comment]
或者菜单往下拉看看有没有其他的内容，用户管理、系统管理之类的

**Comment by MZY888** [comment]
> 或者菜单往下拉看看有没有其他的内容，用户管理、系统管理之类的

没有数据也没有管理之类的
