### ISSUE TITLE
佬，我重新跑了一遍报了个这：java.lang.RuntimeException: 初始化 MenuAutoInitializer 执行失败，原因：unknown

### ISSUE THREAD

**Issue by MZY888** [mrzhqiang/rowing#5]

**Comment by mrzhqiang** [comment]
这种一般不可能出现，除非你对数据做了什么，你心里明白的

**Comment by mrzhqiang** [comment]
数据库表也删了，再重新启动程序

**Comment by MZY888** [comment]
> 数据库表也删了，再重新启动程序

好的，正在重新运行

**Comment by MZY888** [comment]
> 数据库表也删了，再重新启动程序

还是一样的，用的IDEA直接运行会报错，然后DeBug项目之后就不报了，但是就是初始化不了

**Comment by mrzhqiang** [comment]
> > 数据库表也删了，再重新启动程序
> 
> 还是一样的，用的IDEA直接运行会报错，然后DeBug项目之后就不报了，但是就是初始化不了

发一下你删除数据库表后的截图

**Comment by MZY888** [comment]
> > > 数据库表也删了，再重新启动程序
> > 
> > 
> > 还是一样的，用的IDEA直接运行会报错，然后DeBug项目之后就不报了，但是就是初始化不了
> 
> 发一下你删除数据库表后的截图

![QQ截图20240305172903](https://github.com/mrzhqiang/rowing/assets/113449126/97e75cb9-05fb-4a86-b9ed-5d58f7018ecb)

**Comment by mrzhqiang** [comment]
现在运行一下看看，注意一下控制台日志

**Comment by MZY888** [comment]
> 现在运行一下看看，注意一下控制台日志

![QQ截图20240305173542](https://github.com/mrzhqiang/rowing/assets/113449126/275e5793-940a-4f5c-995d-8ba89b675ce0)
现在是这样的

**Comment by MZY888** [comment]
> SQL没必要截图，看看有没有warn或者error日志

![QQ截图20240305173929](https://github.com/mrzhqiang/rowing/assets/113449126/04e17918-4c09-436a-a20e-08c4afefb4d3)
![QQ截图20240305174149](https://github.com/mrzhqiang/rowing/assets/113449126/06fdf50e-fd1e-4f2e-b8e1-8278939f733a)
![QQ截图20240305174204](https://github.com/mrzhqiang/rowing/assets/113449126/b65dc067-d5ad-4513-bac5-738c8d54bdb8)
![QQ截图20240305174216](https://github.com/mrzhqiang/rowing/assets/113449126/9a3b8407-6d3f-425c-b6b9-ce08d359421b)
这有4个

**Comment by MZY888** [comment]
> > SQL没必要截图，看看有没有warn或者error日志
> 
> ![QQ截图20240305173929](https://private-user-images.githubusercontent.com/113449126/310062781-04e17918-4c09-436a-a20e-08c4afefb4d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzIwNzgsIm5iZiI6MTcwOTYzMTc3OCwicGF0aCI6Ii8xMTM0NDkxMjYvMzEwMDYyNzgxLTA0ZTE3OTE4LTRjMDktNDM2YS1hMjBlLTA4YzRhZmVmYjRkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwOTQyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjUwZjZmZGI1YWFlYWQ4MmNkOTg5NGY3MWUzZGJjYjVkOWEyNmNmOTMzMjU1NTU3ZTM5NjBkMjk0OThkMGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WqcYMYVAMqYYR3uw2wsizyaa0o6QNlQSKpSc2vymuFA) ![QQ截图20240305174149](https://private-user-images.githubusercontent.com/113449126/310062791-06fdf50e-fd1e-4f2e-b8e1-8278939f733a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzIwNzgsIm5iZiI6MTcwOTYzMTc3OCwicGF0aCI6Ii8xMTM0NDkxMjYvMzEwMDYyNzkxLTA2ZmRmNTBlLWZkMWUtNGYyZS1iOGUxLTgyNzg5MzlmNzMzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwOTQyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWQzZWViNjcyZWQzYTA1MWExY2EyY2JhNDAwMjU0MTk0NmRjN2ViYzA4ZGQ3OGQ0MjU1NTRjNzAzNGRjMTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-FCcXibA3uOFn5fY3LfQ7FvNd-VyKoYR1tMj4u_0WjY) ![QQ截图20240305174204](https://private-user-images.githubusercontent.com/113449126/310062796-b65dc067-d5ad-4513-bac5-738c8d54bdb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzIwNzgsIm5iZiI6MTcwOTYzMTc3OCwicGF0aCI6Ii8xMTM0NDkxMjYvMzEwMDYyNzk2LWI2NWRjMDY3LWQ1YWQtNDUxMy1iYWM1LTczOGM4ZDU0YmRiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwOTQyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTMyZTM0MGU5YmMxNjNlNmZiZDk3OTg2MmMxYjk3ZDU4OTBlMDU0OGQzZWJmYTcwYzk1OGY3NGUxY2U2OWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZY-cCtOdAWWzagt88gPJ-weURMcTZvGIWBjEsxw7p8Q) ![QQ截图20240305174216](https://private-user-images.githubusercontent.com/113449126/310062802-9a3b8407-6d3f-425c-b6b9-ce08d359421b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzIwNzgsIm5iZiI6MTcwOTYzMTc3OCwicGF0aCI6Ii8xMTM0NDkxMjYvMzEwMDYyODAyLTlhM2I4NDA3LTZkM2YtNDI1Yy1iNmI5LWNlMDhkMzU5NDIxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwOTQyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzJiMjAxYjEzOTQzNGFjYWNmOGQ3Y2U1ZmJjNzk4NGMxZGFhMzhmYzczMzE3YzMxZGQ2MThiMmEzY2QxZjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jRHIwSih-S4PBoHg2qoB8QW4EapmgUMKFz6h4MjCmCk) 这有4个

然后就结束了

**Comment by mrzhqiang** [comment]
![image](https://github.com/mrzhqiang/rowing/assets/18276822/14ceeed3-688e-4874-b015-357695c7b0a7)
这里的报错，请截图完整，包括异常的 cause 也截图出来，不要截一部分...

**Comment by MZY888** [comment]
> ![image](https://private-user-images.githubusercontent.com/18276822/310065284-14ceeed3-688e-4874-b015-357695c7b0a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzI1MjYsIm5iZiI6MTcwOTYzMjIyNiwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNjUyODQtMTRjZWVlZDMtNjg4ZS00ODc0LWIwMTUtMzU3Njk1YzdiMGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5NTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlOWY0MDNiMDdiMDM0ZWZmYzIzOWVjNTIxOWU0NjllYWQ5NzY2OTIxODUyZDk1NjI3ZjhjOWI5YmI0NjQ2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2i2i1a32rBG7OS_LCEsMSQwWzXU9T4Wrc0EDRhXrceM) 这里的报错，请截图完整，包括异常的 cause 也截图出来，不要截一部分...

![QQ截图20240305175232](https://github.com/mrzhqiang/rowing/assets/113449126/b84fa079-3584-4020-bfe1-d465702e4345)

**Comment by MZY888** [comment]
> > ![image](https://private-user-images.githubusercontent.com/18276822/310065284-14ceeed3-688e-4874-b015-357695c7b0a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzI1MjYsIm5iZiI6MTcwOTYzMjIyNiwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNjUyODQtMTRjZWVlZDMtNjg4ZS00ODc0LWIwMTUtMzU3Njk1YzdiMGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5NTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlOWY0MDNiMDdiMDM0ZWZmYzIzOWVjNTIxOWU0NjllYWQ5NzY2OTIxODUyZDk1NjI3ZjhjOWI5YmI0NjQ2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2i2i1a32rBG7OS_LCEsMSQwWzXU9T4Wrc0EDRhXrceM) 这里的报错，请截图完整，包括异常的 cause 也截图出来，不要截一部分...
> 
> ![QQ截图20240305175232](https://private-user-images.githubusercontent.com/113449126/310066443-b84fa079-3584-4020-bfe1-d465702e4345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzI2OTAsIm5iZiI6MTcwOTYzMjM5MCwicGF0aCI6Ii8xMTM0NDkxMjYvMzEwMDY2NDQzLWI4NGZhMDc5LTM1ODQtNDAyMC1iZmUxLWQ0NjU3MDJlNDM0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwOTUzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjljOWMyMjFhNDJlMTJkMTZhNDlhNjRlN2ZjOTVlYTZmYmE0Y2UwNGQ5MjIxMmYyOWMzYmY3NzlmZjkyN2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BmXYxAf0F2nmRR6xt8IStUtmCw0fzNwXjGPw6lWq8l0)

![QQ截图20240305175435](https://github.com/mrzhqiang/rowing/assets/113449126/135fdc8e-33e7-4b48-bf87-5cbebb5fecd7)
![QQ截图20240305175459](https://github.com/mrzhqiang/rowing/assets/113449126/e7fbce88-597e-48ed-b2fc-b58851222627)
![QQ截图20240305175541](https://github.com/mrzhqiang/rowing/assets/113449126/d42b82d0-ae0b-482b-99b4-9be0fa2a8f38)
![QQ截图20240305175603](https://github.com/mrzhqiang/rowing/assets/113449126/56c1e68b-132d-42fb-a09e-1cf10b0e19fa)

**Comment by mrzhqiang** [comment]
OK，大概知道问题在哪里了，稍等，我看看怎么解决

**Comment by mrzhqiang** [comment]
![image](https://github.com/mrzhqiang/rowing/assets/18276822/1bc58870-3956-4de1-844c-4f44824aca6c)
参考这里的 hidden 从 meta 里面转移到外面来，这是最新版本修复的内容，但是最新版本没有测试注册功能，所以你手动调整一下。

**Comment by mrzhqiang** [comment]
> ![image](https://private-user-images.githubusercontent.com/18276822/310071127-1bc58870-3956-4de1-844c-4f44824aca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzM1NjEsIm5iZiI6MTcwOTYzMzI2MSwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNzExMjctMWJjNTg4NzAtMzk1Ni00ZGUxLTg0NGMtNGY0NDgyNGFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjc0NzEzMjU4Zjk1YzY3MDRkZDBiNzliMzZlZmVlYzQ2Njg4YzNiODZlNjhiMDYzZGEzZTJhOTY2NWEwNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06kNOpDj23wshGpfBXyS0EOdk2DtIcRSV8fNDYc44dI) 参考这里的 hidden 从 meta 里面转移到外面来，这是最新版本修复的内容，但是最新版本没有测试注册功能，所以你手动调整一下。

文件在：resources/data/menu-routes.json，roles 的 MANAGER 不要改，你还是原来的 ADMIN 就好。

**Comment by MZY888** [comment]
> > ![image](https://private-user-images.githubusercontent.com/18276822/310071127-1bc58870-3956-4de1-844c-4f44824aca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzM1NjEsIm5iZiI6MTcwOTYzMzI2MSwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNzExMjctMWJjNTg4NzAtMzk1Ni00ZGUxLTg0NGMtNGY0NDgyNGFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjc0NzEzMjU4Zjk1YzY3MDRkZDBiNzliMzZlZmVlYzQ2Njg4YzNiODZlNjhiMDYzZGEzZTJhOTY2NWEwNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06kNOpDj23wshGpfBXyS0EOdk2DtIcRSV8fNDYc44dI) 参考这里的 hidden 从 meta 里面转移到外面来，这是最新版本修复的内容，但是最新版本没有测试注册功能，所以你手动调整一下。
> 
> 文件在：resources/data/menu-routes.json，roles 的 MANAGER 不要改，你还是原来的 ADMIN 就好。

好的，我试试

**Comment by MZY888** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/18276822/310071127-1bc58870-3956-4de1-844c-4f44824aca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzM1NjEsIm5iZiI6MTcwOTYzMzI2MSwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNzExMjctMWJjNTg4NzAtMzk1Ni00ZGUxLTg0NGMtNGY0NDgyNGFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjc0NzEzMjU4Zjk1YzY3MDRkZDBiNzliMzZlZmVlYzQ2Njg4YzNiODZlNjhiMDYzZGEzZTJhOTY2NWEwNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06kNOpDj23wshGpfBXyS0EOdk2DtIcRSV8fNDYc44dI) 参考这里的 hidden 从 meta 里面转移到外面来，这是最新版本修复的内容，但是最新版本没有测试注册功能，所以你手动调整一下。
> > 
> > 
> > 文件在：resources/data/menu-routes.json，roles 的 MANAGER 不要改，你还是原来的 ADMIN 就好。
> 
> 好的，我试试

意思是把这里面的代码复制替换掉吗

**Comment by MZY888** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/18276822/310071127-1bc58870-3956-4de1-844c-4f44824aca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzM1NjEsIm5iZiI6MTcwOTYzMzI2MSwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNzExMjctMWJjNTg4NzAtMzk1Ni00ZGUxLTg0NGMtNGY0NDgyNGFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjc0NzEzMjU4Zjk1YzY3MDRkZDBiNzliMzZlZmVlYzQ2Njg4YzNiODZlNjhiMDYzZGEzZTJhOTY2NWEwNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06kNOpDj23wshGpfBXyS0EOdk2DtIcRSV8fNDYc44dI) 参考这里的 hidden 从 meta 里面转移到外面来，这是最新版本修复的内容，但是最新版本没有测试注册功能，所以你手动调整一下。
> > > 
> > > 
> > > 文件在：resources/data/menu-routes.json，roles 的 MANAGER 不要改，你还是原来的 ADMIN 就好。
> > 
> > 
> > 好的，我试试
> 
> 意思是把这里面的代码复制替换掉吗

看懂了

**Comment by MZY888** [comment]
> ![image](https://private-user-images.githubusercontent.com/18276822/310071127-1bc58870-3956-4de1-844c-4f44824aca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzM1NjIsIm5iZiI6MTcwOTYzMzI2MiwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNzExMjctMWJjNTg4NzAtMzk1Ni00ZGUxLTg0NGMtNGY0NDgyNGFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwMDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyM2VhYTJjZjQ3MjRlNjFlOWNlZGJiODg4N2Q5MGVjNTAxNzhkZmNmOTI3NzUzMWFiZDAwMDk5M2U3MzhjYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hPuQLHavgRTdHdr1pQZ9nTCwEOWKLX5OOk7uPK9H8BY) 参考这里的 hidden 从 meta 里面转移到外面来，这是最新版本修复的内容，但是最新版本没有测试注册功能，所以你手动调整一下。


> ![image](https://private-user-images.githubusercontent.com/18276822/310071127-1bc58870-3956-4de1-844c-4f44824aca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzcxNzIsIm5iZiI6MTcwOTYzNjg3MiwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNzExMjctMWJjNTg4NzAtMzk1Ni00ZGUxLTg0NGMtNGY0NDgyNGFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZTMyMTI3YmI0ZWFmNWUwNmNiYjdkODdmYTNmMGVkMmIzZWMwYjUyZWNkY2YxZjhkZjBhMzllZGJjNDFjODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lo0VSwddG7_Bm95Iv9u-t1hL5aLfw1ogLFGyxXJHksA) 参考这里的 hidden 从 meta 里面转移到外面来，这是最新版本修复的内容，但是最新版本没有测试注册功能，所以你手动调整一下。

佬，还是不行一模一样的错，把数据表删了重新跑也是一样的

**Comment by MZY888** [comment]
> > ![image](https://private-user-images.githubusercontent.com/18276822/310071127-1bc58870-3956-4de1-844c-4f44824aca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzM1NjEsIm5iZiI6MTcwOTYzMzI2MSwicGF0aCI6Ii8xODI3NjgyMi8zMTAwNzExMjctMWJjNTg4NzAtMzk1Ni00ZGUxLTg0NGMtNGY0NDgyNGFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjc0NzEzMjU4Zjk1YzY3MDRkZDBiNzliMzZlZmVlYzQ2Njg4YzNiODZlNjhiMDYzZGEzZTJhOTY2NWEwNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06kNOpDj23wshGpfBXyS0EOdk2DtIcRSV8fNDYc44dI) 参考这里的 hidden 从 meta 里面转移到外面来，这是最新版本修复的内容，但是最新版本没有测试注册功能，所以你手动调整一下。
> 
> 文件在：resources/data/menu-routes.json，roles 的 MANAGER 不要改，你还是原来的 ADMIN 就好。

是要用最新版来跑吗

**Comment by mrzhqiang** [comment]
版本别改，文件你改完截图我看看，截图截图截图

**Comment by MZY888** [comment]
> 版本别改，文件你改完截图我看看，截图截图截图

![QQ截图20240305191629](https://github.com/mrzhqiang/rowing/assets/113449126/d66f391c-2e3a-4014-aef2-e377b02c65e1)
是这样吧

**Comment by mrzhqiang** [comment]
是这样。那你控制台报错信息截图出来看看。

**Comment by MZY888** [comment]
> 是这样。那你控制台报错信息截图出来看看。

![QQ截图20240305192700](https://github.com/mrzhqiang/rowing/assets/113449126/8e6c501f-24eb-4264-a260-e72586647f21)
![QQ截图20240305192717](https://github.com/mrzhqiang/rowing/assets/113449126/e7261857-02cf-4cbb-bed8-6e7cdd8a80cb)
![QQ截图20240305192733](https://github.com/mrzhqiang/rowing/assets/113449126/a178df6c-2fa0-4af8-9176-eaf2a28ec4b1)
![QQ截图20240305192756](https://github.com/mrzhqiang/rowing/assets/113449126/91d5f2f1-079d-45e2-b891-f3b4e14f17ba)
![QQ截图20240305192815](https://github.com/mrzhqiang/rowing/assets/113449126/c2423441-c560-4dcc-b683-25d5727bfd81)
![QQ截图20240305192823](https://github.com/mrzhqiang/rowing/assets/113449126/d1c79bd2-7b60-4286-b169-4977b2c86cc4)

**Comment by mrzhqiang** [comment]
文件不存在啊，你看看data目录文件名是不是一样

**Comment by MZY888** [comment]
> > > 文件不存在啊，你看看data目录文件名是不是一样
> > 
> > 
> > 一样的
> 
> 你再确认一下吧，很明显和控制台报错的文件名不一样。。。

也没改过呀

**Comment by mrzhqiang** [comment]
> > > > 文件不存在啊，你看看data目录文件名是不是一样
> > > 
> > > 
> > > 一样的
> > 
> > 你再确认一下吧，很明显和控制台报错的文件名不一样。。。
> 
> 也没改过呀

你改一下

**Comment by MZY888** [comment]
> > > > > 文件不存在啊，你看看data目录文件名是不是一样
> > > > 
> > > > 
> > > > 一样的
> > > 
> > > 
> > > 你再确认一下吧，很明显和控制台报错的文件名不一样。。。
> > 
> > 
> > 也没改过呀
> 
> 你改一下

管理系统出来了，这么多天麻烦您了

**Comment by mrzhqiang** [comment]
> > > > > > 文件不存在啊，你看看data目录文件名是不是一样
> > > > > 
> > > > > 
> > > > > 一样的
> > > > 
> > > > 
> > > > 你再确认一下吧，很明显和控制台报错的文件名不一样。。。
> > > 
> > > 
> > > 也没改过呀
> > 
> > 你改一下
> 
> 管理系统出来了，这么多天麻烦您了

没事，你有问题就提出来，我看到会回复
